### ISSUE TITLE
Serve from HTTPS

### ISSUE THREAD

**Issue by cvan** [toji/webvr.info#7]
I see that http://webvr.info is served from GitHub Pages (https://toji.github.io/webvr.info/). Could you get https://webvr.info set up?

**Comment by cvan** [comment]
If you'd like, I can set this up so we can serve from HTTPS. Let me know.

**Comment by toji** [comment]
I'd actually like to do it myself for educational purposes, but don't really know where to start. I'd appreciate pointers!

**Comment by cvan** [comment]
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by toji** [comment]
Okay, set up the DNS with CloudFlare. Usual "can take up to 24 hours to apply" caveats. Need to watch the page today to make sure it doesn't break.

**Comment by toji** [comment]
Okay, looks like the upgrade is working. (Seeing it come through correctly on my end at least, probably still propagating.) Gonna close this ticket. Thanks for the pointers!

(Also: https://github.com/toji/webvr.info/commit/a413dd5174f90a15023bb8adfd230b69ee57888a ಠ_ಠ)
