### ISSUE TITLE
Update sample canvas color randomization to work with new Chrome code

### ISSUE THREAD

**Issue by weableandbob** [toji/webvr.info#76]
Since [this](https://bugs.chromium.org/p/chromium/issues/detail?id=716571) Chromium issue was fixed, the canvas no longer receives an onClick for either Cardboard clicks or the Daydream controller's touchpad button. Instead, both show up as controller input via the Gamepad API. The samples should be updated to randomize the canvas color on this controller input so that the end behavior of changing color when you tap the screen/press the button is unchanged.

**Comment by mkeblx** [comment]
This can be closed, as samples updated with `VRSamplesUtil.addVRClickListener`
