### ISSUE TITLE
How does webvr.info get around the WebVR flag when disabled?

### ISSUE THREAD

**Issue by rjsteinert** [toji/webvr.info#92]
Why does this work (https://webvr.info/samples/03-vr-presentation.html) but on another tab on the same device this (https://rjsteinert.github.io/webvr.info/samples/03-vr-presentation.html) results in "ERROR: Your browser does not support WebVR."? All I did was fork this repo and then set master to publish on github pages. 

Perhaps webvr.info is not based on master branch?

**Comment by rjsteinert** [comment]
Btw, I'm using a Pixel 2 with Chrome 65.

**Comment by rjsteinert** [comment]
Inspecting using Chrome remote debugging, I see this message is reached because `navigator.getVRDisplays` is `undefined` at https://rjsteinert.github.io/webvr.info/samples/03-vr-presentation.html but a function at `https://webvr.info/samples/03-vr-presentation.html`.

**Comment by rjsteinert** [comment]
Hmm, no difference between what is on the webvr.info server and what is in master branch.

<img width="1320" alt="screen shot 2018-03-17 at 12 52 35 pm" src="https://user-images.githubusercontent.com/156575/37557919-2e1669a2-29e2-11e8-9c1c-fc51f38e62f3.png">

**Comment by rjsteinert** [comment]
After enabling the WebVR flag, (https://rjsteinert.github.io/webvr.info/samples/03-vr-presentation.html now works as expected. How does https://webvr.info/samples/03-vr-presentation.html get around the WebVR flag in disabled mode? 

<img width="478" alt="screen shot 2018-03-17 at 12 54 31 pm" src="https://user-images.githubusercontent.com/156575/37557945-78037e7e-29e2-11e8-9e48-fa92be6022d5.png">

**Comment by rjsteinert** [comment]
Oooooh you have to be part of the Origin Trial https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md

**Comment by cvan** [comment]
Yep, it's via the Origin Trial tokens in the `<meta>` tags. https://webvr.rocks/chrome_for_android#what_is_the_webvr_origin_trial has more info.

Hope that helps!
